// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE63ftd_e4LdCUoYQTjNetd2k9lx1vtw8',
    appId: '1:268538141692:web:a73e1b003b744fdcf5f079',
    messagingSenderId: '268538141692',
    projectId: 'kitsain-a3bee',
    authDomain: 'kitsain-a3bee.firebaseapp.com',
    storageBucket: 'kitsain-a3bee.appspot.com',
    measurementId: 'G-BE388NCRBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9u8txJcCIl84mIyZokJXJy3oRsppjq8s',
    appId: '1:268538141692:android:7303124d6a0ee68cf5f079',
    messagingSenderId: '268538141692',
    projectId: 'kitsain-a3bee',
    storageBucket: 'kitsain-a3bee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUd5iS9PMqjDEMpfqNNGs_p8nshPyOjzM',
    appId: '1:268538141692:ios:8f9fb5b9070640aef5f079',
    messagingSenderId: '268538141692',
    projectId: 'kitsain-a3bee',
    storageBucket: 'kitsain-a3bee.appspot.com',
    iosClientId: '268538141692-dci565p16spfkac3h5jdeu7q7qbdjr0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitsainFrontendSpring2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUd5iS9PMqjDEMpfqNNGs_p8nshPyOjzM',
    appId: '1:268538141692:ios:8f9fb5b9070640aef5f079',
    messagingSenderId: '268538141692',
    projectId: 'kitsain-a3bee',
    storageBucket: 'kitsain-a3bee.appspot.com',
    iosClientId: '268538141692-dci565p16spfkac3h5jdeu7q7qbdjr0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitsainFrontendSpring2023',
  );
}
